name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Get App Store Connect API Key File
        env:
          ASCAPI_KEY: ${{ secrets.ASCAPI_KEY }}
        run: |
          KEY_PATH=$RUNNER_TEMP/ascapi-key.p8
          
          echo -n "$ASCAPI_KEY" > $KEY_PATH

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -scheme BAGen -configuration Debug

      - name: Archive
        env:
          ASCAPI_KEY_ID: ${{ secrets.ASCAPI_KEY_ID }}
          ASCAPI_ISSUER_ID: ${{ secrets.ASCAPI_ISSUER_ID }}
        run: |
          KEY_PATH=$RUNNER_TEMP/ascapi-key.p8
          
          xcodebuild -scheme BAGen -configuration Debug DEVELOPMENT_TEAM=B57D8PP775 -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath app.xcarchive clean archive CODE_SIGN_IDENTITY="Apple Development" -allowProvisioningUpdates -authenticationKeyPath $KEY_PATH -authenticationKeyID $ASCAPI_KEY_ID -authenticationKeyIssuerID $ASCAPI_ISSUER_ID
        
      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath app.xcarchive -exportPath ./ -exportOptionsPlist ExportOptions.plist

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ipa
          path: ./*.ipa
